### ISSUE TITLE
Comments for Basic 2D Rasterization

### ISSUE THREAD

**Issue by magcius** [magcius/xplain#28]
http://magcius.github.io/xplain/article/rast1.html

**Comment by yarwelp** [comment]
Very interesting article. Well written and it answers several questions that I've had but which I hadn't previously gotten around to investigate. Looking forward to the next article in the series.

**Comment by ghost** [comment]
Great article. If you weren't going to already, I'd suggest covering sRGB, as it's fundamental for correct interpolation of color gradients (and AFAIK for correct alpha blending as well).

**Comment by magcius** [comment]
> I'd suggest covering sRGB, as it's fundamental for correct interpolation of color gradients (and AFAIK for correct alpha blending as well).

The biggest issue is that since this is the web, I'm constrained to web APIs, and the web APIs managing color are... uh... poor, to say the least.

The official HTML5 spec says this on canvas color spaces:
https://html.spec.whatwg.org/multipage/scripting.html#colour-spaces-and-colour-correction

But according to this thread on whatwg, this is an inaccurate summary of what browsers do:
https://lists.w3.org/Archives/Public/public-whatwg-archive/2014May/0164.html

Wide gamut support is coming soon:
https://github.com/WICG/canvas-color-space/blob/master/CanvasColorSpaceProposal.md
https://bugs.chromium.org/p/chromium/issues/detail?id=634542

I'll have to do my own tests, but it's probably correct that when using `putImageData`, the values are *not* linear, so a linear interpolation gets us junk. But I don't know if it's sRGB or the output profile space, and if it's the latter, I don't know if I *can* pull the color space out to properly blend.

Thanks for the recommendation, though! It's definitely a *huge* thing I gloss over in the article itself, making the simplification that color is linear. That is totally wrong and should correct it in a follow-up. :)

**Comment by smurfix** [comment]
Why are you using a fourth-order smoothstep function? It's supposed to be symmetric around (0.5,0.5) so `t^2(3-2t)` makes more sense IMHO.

**Comment by smurfix** [comment]
You wrote that you're using `t*t*(3 - t*2)` as a smoothstep function. That doesn't make sense, as the first derivative at t=1 is not zero. You want `t*t*(3 - 2t)`.

**Comment by magcius** [comment]
I'm not sure I understand. How is `t*2` different from `2t`?

**Comment by smurfix** [comment]
sorry, my brain fart.

**Comment by metroidchild** [comment]
I'd enjoy all sorts of random fun in other interactive demos, whether it be compression algorithms or anything else, I like the format

**Comment by metroidchild** [comment]
I'd enjoy all sorts of random fun in other interactive demos, whether it be compression algorithms or anything else, I like the format

**Comment by valsoray17** [comment]
Amazing article! Very informative and fascinating! Thank you.

One question: shouldn't it be  `coverage /= nSubpixelsX * nSubpixelsY;`?  in the 
```
// Take the average of all subpixels.
coverage /= nSubpixelsY * nSubpixelsY;
```
It's irrelevant for a square grid, but can it be non-square?

**Comment by magcius** [comment]
Good eye! Yep, that's a typo. Fixed in 770ac99b9b5c5a81de3b3c6c9330fd55a3cf25ac. In the actual demo code, it's correct: https://github.com/magcius/xplain/blob/gh-pages/src/article-demos/rast1.js#L242

**Comment by duckworthd** [comment]
As with the others on X Window System, beautifully written! I look forward to your upcoming work.

The part of graphics I've always found puzzling is how a 3d scene is rasterized to 2d. Questions like "how do you decide which object is in front?" or "how is shading and lighting handled?" or "how do you map a 2d texture onto a 3d object?" are all questions I still have after all these years. At some point, I should just open a textbook!

**Comment by magcius** [comment]
You're partially in luck. I've mostly moved on from Xplain as a format for explaining things, and my career has moved from open-source Linux graphics to working in the games industry. I'm still interested in explaining things, and I've started some content recently that might interest you, with an eye towards 3D graphics. Some links:

https://noclip.website/
https://blog.mecheye.net/2018/03/deconstructing-the-water-effect-in-super-mario-sunshine/
https://www.youtube.com/watch?v=8rCRsOLiO7k

**Comment by naikrovek** [comment]
holy butts, please continue to write like this.  I don't care if it's about X or what.

**Comment by ChrisG-HGH** [comment]
Awesomely well written! I've been using various incarnations of the X Window System since 1990 but never really understood how it worked until now!  Thank you! 

Could you please write a short article explaining just what the heck Wayland and Mir are, in a short simple manner for someone who has just read your xplain and learned what an X Server is?

EDIT: to answer my own question a little bit, I found this short article.  Not as well written as yours, but having read your work, I can now understand this article: https://discourse.ubuntu.com/t/ok-so-what-is-this-wayland-thing-anyway/8484

**Comment by dataf3l** [comment]
I love this content!
